       IDENTIFICATION DIVISION.
       PROGRAM-ID. Colors.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       SCREEN SECTION.
       01 S-COLORTST-SCR
           BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 BLANK SCREEN.
           05 LINE 01.
              10 COL 1 VALUE
           'LOWLIGHT -------- HIGHLIGHT LOWLIGHT -------- HIGHLIGHT'.
           05 LINE + 1.
               10 COL 1 VALUE
           '-------- -------- -------- -------- -------- --------'.
           05 LINE + 1.
               10 COL 1 VALUE
           '-------- -------- -------- REVERSE REVERSE REVERSE'.
           05 LINE + 1.
               10 COL 1 VALUE
           '01234567 01234567 01234567 01234567 01234567 01234567'.
           05 LINE + 1.
               10 COL 1 VALUE '0 0 0 0 0 0 '.
           05 LINE + 1.
               10 COL 1 VALUE '1 1 1 1 1 1 '.
           05 LINE + 1.
               10 COL 1 VALUE '2 2 2 2 2 2 '.
           05 LINE + 1.
               10 COL 1 VALUE '3 1 3 2 3 3 3 4 3 5 3 6 '.
           05 LINE + 1.
           10 COL 1 VALUE '4 4 4 4 4 4 '.
           05 LINE + 1.
           10 COL 1 VALUE '5 5 5 5 5 5 '.
           05 LINE + 1.
           10 COL 1 VALUE '6 6 6 6 6 6 '.
           05 LINE + 1.
           10 COL 1 VALUE '7 7 7 7 7 7 '.
           05 LINE + 1.
           10 COL 1 VALUE
           ' LOWLIGHT -------- HIGHLIGHT LOWLIGHT -------- HIGHLIGHT'.
           05 LINE + 1.
           10 COL 1 VALUE ' BLINK BLINK BLINK BLINK BLINK BLINK'.
           05 LINE + 1.
           10 COL 1 VALUE
           ' -------- -------- -------- REVERSE REVERSE REVERSE'.
           05 LINE + 1.
           10 COL 1 VALUE
           ' 01234567 01234567 01234567 01234567 01234567 01234567'.
           05 LINE + 1.
           10 COL 1 VALUE '0 0 0 0 0 0 '.
           05 LINE + 1.
           10 COL 1 VALUE '1 1 1 1 1 1 '.
           05 LINE + 1.
           10 COL 1 VALUE '2 2 2 2 2 2 '.
           05 LINE + 1.
           10 COL 1 VALUE '3 7 3 8 3 9 3 10 3 11 3 12 '.
           05 LINE + 1.
           10 COL 1 VALUE '4 4 4 4 4 4 '.
           05 LINE + 1.
           10 COL 1 VALUE '5 5 5 5 5 5 '.
           05 LINE + 1.
           10 COL 1 VALUE '6 6 6 6 6 6 '.
           05 LINE + 1.
           *> #1
       05 LINE 05.
           10 COL 2 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 2 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 LOWLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 LOWLIGHT
               VALUE 'X'.
           *> #2
       05 LINE 05.
           10 COL 12 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 VALUE 'X'.
           *> #3
       05 LINE 05.
           10 COL 22 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT
               VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT
           VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT
           VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT
           VALUE 'X'.
           *> #4
       05 LINE 05.
           10 COL 32 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           LOWLIGHT REVERSE-VIDEO VALUE 'X'.
           *> #5
       05 LINE 05.
           10 COL 42 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
           05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           REVERSE-VIDEO VALUE 'X'.
           *> #6
       05 LINE 05.
           10 COL 52 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           HIGHLIGHT REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT
           REVERSE-VIDEO VALUE 'X'.
           *> #7
       05 LINE 17.
           10 COL 02 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 02 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           LOWLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           LOWLIGHT BLINK VALUE 'X'.
           *> #8
       05 LINE 17.
           10 COL 12 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7 BLINK
               VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7 BLINK
               VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7 BLINK
               VALUE 'X'.
           10 COL 12 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 BLINK
               VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 12 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 BLINK
               VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           BLINK VALUE 'X'.
           *> #9
       05 LINE 17.
           10 COL 22 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
       05 LINE + 1.
           10 COL 22 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK VALUE 'X'.
           *> #10
       05 LINE 17.
           10 COL 32 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 32 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           LOWLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           *> #11
       05 LINE 17.
           10 COL 42 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 42 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6
           BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7
           BLINK REVERSE-VIDEO VALUE 'X'.
           *> #12
       05 LINE 17.
           10 COL 52 BACKGROUND-COLOR 0 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 0 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 1 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 1 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 2 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 1
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 2
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 3
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 4
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 5
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 6
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 2 FOREGROUND-COLOR 7
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
       05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 3 FOREGROUND-COLOR 0
           HIGHLIGHT BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 1 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 2 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 3 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 4 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 5 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 6 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 3 FOREGROUND-COLOR 7 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 4 FOREGROUND-COLOR 0 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 1 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 2 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 3 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 4 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 5 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 6 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 4 FOREGROUND-COLOR 7 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 5 FOREGROUND-COLOR 0 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 1 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 2 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 3 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 4 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 5 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 6 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 5 FOREGROUND-COLOR 7 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 6 FOREGROUND-COLOR 0 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 1 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 2 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 3 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 5 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 6 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 6 FOREGROUND-COLOR 7 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           05 LINE + 1.
           10 COL 52 BACKGROUND-COLOR 7 FOREGROUND-COLOR 0 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 1 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 2 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 3 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 4 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 5 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 6 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
           10 COL + 1 BACKGROUND-COLOR 7 FOREGROUND-COLOR 7 HIGHLIGHT
               BLINK REVERSE-VIDEO VALUE 'X'.
       PROCEDURE DIVISION.
           000-Main SECTION.
           DISPLAY S-COLORTST-SCR.
           STOP RUN.
